In [1]:
path = 'https://raw.githubusercontent.com/tec03/Datasets/main/datasets/fpEg1.csv'

In [2]:
pip install pandas

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (1.24.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(path, 
                header = None)
df

   0  1  2  3  4    5    6    7
0  a  c  d  f  g    i    m    p
1  a  b  c  f  l    m    o  NaN
2  b  f  h  j  o  NaN  NaN  NaN
3  b  c  k  s  p  NaN  NaN  NaN
4  a  c  e  f  i    p    m    n

In [6]:
ndf = df.applymap(str)
trans = ndf.values.tolist()
trans

[['a', 'c', 'd', 'f', 'g', 'i', 'm', 'p'],
 ['a', 'b', 'c', 'f', 'l', 'm', 'o', 'nan'],
 ['b', 'f', 'h', 'j', 'o', 'nan', 'nan', 'nan'],
 ['b', 'c', 'k', 's', 'p', 'nan', 'nan', 'nan'],
 ['a', 'c', 'e', 'f', 'i', 'p', 'm', 'n']]

In [8]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 16.3 MB/s eta 0:00:0000:010:01
Collecting joblib>=0.13.2
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 25.9 MB/s eta 0:00:00
Collecting scipy>=1.2.1
  Downloading scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 39.2 MB/s eta 0:00:0000:0100:01
Collecting scikit-learn>=1.0.2
  Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 68.0 MB/s eta 0:00:00:00:0100:01
Requirement already satisfied: numpy>=1.16.2 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from mlxtend) (1.24.2)
Requirement already satisfied: pandas>=0.24.2 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from mlxtend) (1.5.3)
Collecting matplotlib>=3.0.0
  Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 60.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: setuptools in /srv/conda/envs/notebook/lib/python3.10/site-packages (from mlxtend) (67.1.0)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 30.1 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (23.0)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 12.6 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 68.5 MB/s eta 0:00:00
Collecting pillow>=6.2.0
  Downloading Pillow-9.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 42.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.7 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.39.0-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.2 MB/s eta 0:00:00:00:01
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas>=0.24.2->mlxtend) (2022.7.1)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: threadpoolctl, scipy, pyparsing, pillow, kiwisolver, joblib, fonttools, cycler, contourpy, scikit-learn, matplotlib, mlxtend
Successfully installed contourpy-1.0.7 cycler-0.11.0 fonttools-4.39.0 joblib-1.2.0 kiwisolver-1.4.4 matplotlib-3.7.1 mlxtend-0.21.0 pillow-9.4.0 pyparsing-3.0.9 scikit-learn-1.2.2 scipy-1.10.1 threadpoolctl-3.1.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
from mlxtend.preprocessing import TransactionEncoder

In [10]:
te = TransactionEncoder()
te_ary = te.fit(trans).transform(trans)

In [13]:
encodedDF = pd.DataFrame(te_ary,
                        columns = te.columns_)
encodedDF

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,nan,o,p,s
0,True,False,True,True,False,True,True,False,True,False,False,False,True,False,False,False,True,False
1,True,True,True,False,False,True,False,False,False,False,False,True,True,False,True,True,False,False
2,False,True,False,False,False,True,False,True,False,True,False,False,False,False,True,True,False,False
3,False,True,True,False,False,False,False,False,False,False,True,False,False,False,True,False,True,True
4,True,False,True,False,True,True,False,False,True,False,False,False,True,True,False,False,True,False

In [18]:
first10 = encodedDF#.head(10)
ndf = first10.copy()
ndf

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,nan,o,p,s
0,True,False,True,True,False,True,True,False,True,False,False,False,True,False,False,False,True,False
1,True,True,True,False,False,True,False,False,False,False,False,True,True,False,True,True,False,False
2,False,True,False,False,False,True,False,True,False,True,False,False,False,False,True,True,False,False
3,False,True,True,False,False,False,False,False,False,False,True,False,False,False,True,False,True,True
4,True,False,True,False,True,True,False,False,True,False,False,False,True,True,False,False,True,False

In [19]:
ndf = ndf.drop('nan', axis = 1)
ndf.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 's'],
      dtype='object')

## FP frowth algorithm

In [22]:
from mlxtend.frequent_patterns import fpgrowth, association_rules

In [23]:
freq_itms = fpgrowth(ndf,
                     min_support = 0.6,
                     use_colnames = True)
freq_itms

    support      itemsets
0       0.8           (f)
1       0.8           (c)
2       0.6           (p)
3       0.6           (m)
4       0.6           (a)
5       0.6           (b)
6       0.6        (f, c)
7       0.6        (c, p)
8       0.6        (m, c)
9       0.6        (f, m)
10      0.6     (f, m, c)
11      0.6        (a, m)
12      0.6        (a, c)
13      0.6        (a, f)
14      0.6     (a, m, c)
15      0.6     (a, f, m)
16      0.6     (a, f, c)
17      0.6  (a, f, m, c)

In [24]:
as_rules = association_rules(freq_itms,
                             metric = 'lift',
                             min_threshold = 1.5)
as_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
1,(m),"(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
2,(a),(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
3,(m),(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
4,"(a, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
5,"(m, c)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
6,(a),"(m, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
7,(m),"(a, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
8,"(a, f)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
9,"(f, m)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
10,(a),"(f, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
11,(m),"(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
12,"(f, c)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
13,(a),"(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
14,"(a, f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
15,"(f, m, c)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
16,"(a, f)","(m, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
17,"(a, m)","(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
18,"(a, c)","(f, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
19,"(f, m)","(a, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(f, c)","(a, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,"(m, c)","(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,(a),"(f, m, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
23,(m),"(a, f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

CASO 1: Which are the top 10 frequent patterns with high confidence?

In [28]:
SortConf = as_rules.sort_values('confidence',
                                  ascending = False).head(5)
SortConf

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
1,(m),"(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,(a),"(f, m, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,"(m, c)","(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(f, c)","(a, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

Caso 2: Transactions with ascendents (m):

In [33]:
SortConf

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
1,(m),"(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,(a),"(f, m, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,"(m, c)","(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(f, c)","(a, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [32]:
SortConf[SortConf['antecedents'] == {'m'}]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(m),"(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

Caso 3: Transactons without (c, f) antecedents, and (m) consequents

In [35]:
ante = SortConf['antecedents'] == frozenset({'f', 'c'})
ante

0      True
1     False
22    False
21    False
20     True
Name: antecedents, dtype: bool

In [37]:
SortConf[ante]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(f, c)","(a, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [40]:
cons = SortConf['consequents'] == frozenset({'m'})

In [42]:
SortConf[cons]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [43]:
nos = (ante & cons)

In [47]:
SortConf[-nos]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(m),"(f, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,(a),"(f, m, c)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,"(m, c)","(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(f, c)","(a, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

Caso 4: Transactions with at least 2 antecedents

In [48]:
SortConf['ante_len'] = SortConf['antecedents'].apply(lambda x : len(x))

In [54]:
SortConf[
    (SortConf['ante_len'] >= 2) &
    (SortConf['ante_len'] < 3)
]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,ante_len
0,"(f, c)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf,2
21,"(m, c)","(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf,2
20,"(f, c)","(a, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf,2